<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class JuniorERPDashboardBundleEntityClientProxy extends \JuniorERP\DashboardBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setSociete($societe)
    {
        $this->__load();
        return parent::setSociete($societe);
    }

    public function getSociete()
    {
        $this->__load();
        return parent::getSociete();
    }

    public function setFonction($fonction)
    {
        $this->__load();
        return parent::setFonction($fonction);
    }

    public function getFonction()
    {
        $this->__load();
        return parent::getFonction();
    }

    public function addEtude(\JuniorERP\DashboardBundle\Entity\Etude $etudes)
    {
        $this->__load();
        return parent::addEtude($etudes);
    }

    public function getEtudes()
    {
        $this->__load();
        return parent::getEtudes();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTelPortable($telPortable)
    {
        $this->__load();
        return parent::setTelPortable($telPortable);
    }

    public function getTelPortable()
    {
        $this->__load();
        return parent::getTelPortable();
    }

    public function setTelFixe($telFixe)
    {
        $this->__load();
        return parent::setTelFixe($telFixe);
    }

    public function getTelFixe()
    {
        $this->__load();
        return parent::getTelFixe();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'prenom', 'email', 'telPortable', 'telFixe', 'societe', 'fonction', 'refClient', 'etudes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}